# Copyright (c) 2015-2020 Jiaqi Liu (https://github.com/QubitPi)

# Mostly copied from ./build-docs-pdf.yml
---
name: Documentation CI/CD

#on:
#  pull_request:
#  push:
#    branches: [master]

env:
  USER: QubitPi
  EMAIL: jack20220723@gmail.com

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Increase number of watchers to fix generation
      - run: sudo sysctl -w fs.inotify.max_user_watches=524288

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Configure Ruby to build Jekyll site
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
      - name: Ruby gem cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle Setup
        run: bundle config path ${{ github.workspace }}/vendor/bundle
      - name: Bundle Install
        run: bundle install --jobs 4 --retry 3

      # Configure Node to build assets
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      # Build the Docs
      - name: Build Docs
        run: |
          npm ci
          cp .env.example .env
          exe/build

      - name: Deploy documentation to GitHub Pages
        # if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          enable_jekyll: false
          user_name: ${{ env.USER }}
          user_email: ${{ env.EMAIL }}
